### ISSUE TITLE
Usage with fancontrol

### ISSUE THREAD

**Issue by maxekman** [jonasmalacofilho/liquidtux#3]
I tried out this mod with Manjaro and it works great, getting the liquid temp and fan speeds showing up in sensors. However when I try to configure fancontrol (manually) it will not work as it thinks it’s a PWM fan. I can post more detailed config and error messages later.

In the meantime, any suggestions for how to make fancontrol control the X52 (in my case)?

Thanks,
Max

**Comment by jonasmalacofilho** [comment]
No need for more info, his happens because I haven't implemented the necessary `pwm` attributes yet.  It's something I'm still planing to do, but I have to admit it isn't a priority right now.

In the meantime, you can use [liquidctl](https://github.com/jonasmalacofilho/liquidctl) to set fan/pump profiles based on liquid temperature (as long as your X52 is running a somewhat recent firmware).  You can also take a look at liquidctl's experimental ["yoda"](https://github.com/jonasmalacofilho/liquidctl/issues/72#issuecomment-581198492) script for fan/pump control based on other sensors.

**Comment by maxekman** [comment]
Thanks for the tips! I’m currently running liquidctl with systemd, works really well. Will check out the yoda script to try to control the fans from CPU temp then.
